language: node_js
node_js:
  - 12.2.0
cache: yarn
script: yarn test
deploy:
  matrix:
    - provider: script
      script:
        netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --dir
        ./client/build --prod
      skip_cleanup: true
      on:
        branch: master
    - provider: heroku
      api_key:
        secure: $HEROKU_API_KEY
      app: issuestracker-tb
